name = "cloudflare-template"
compatibility_date = "2025-03-19"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "vankvaultdb"
database_id = "6d1284b8-b06f-4bd9-a6d3-2d0623215577"